
package org.thriftbook;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TradeHistory", targetNamespace = "http://thriftbook.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TradeHistory {


    /**
     * 
     * @param symbol
     * @return
     *     returns org.thriftbook.TradeReport
     */
    @WebMethod(operationName = "get_last_sale")
    @WebResult(partName = "return")
    public TradeReport getLastSale(
        @WebParam(name = "symbol", partName = "symbol")
        String symbol);

}
